// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_nWGGW4qhFKKx0jSQyOmkV9aQRXyZkXo',
    appId: '1:243632724029:web:0781910fabb9f319f47254',
    messagingSenderId: '243632724029',
    projectId: 'recipe-app-33f1d',
    authDomain: 'recipe-app-33f1d.firebaseapp.com',
    storageBucket: 'recipe-app-33f1d.appspot.com',
    measurementId: 'G-0M80MLJHDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG8KYwP0o5Z7ME_-aklvtpMCtY_bcFUCw',
    appId: '1:243632724029:android:3428e4504bdb8111f47254',
    messagingSenderId: '243632724029',
    projectId: 'recipe-app-33f1d',
    storageBucket: 'recipe-app-33f1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz76t1Uq4GbbKIf1V9RyaZ085y-njSlYM',
    appId: '1:243632724029:ios:5991dcae7700ceb6f47254',
    messagingSenderId: '243632724029',
    projectId: 'recipe-app-33f1d',
    storageBucket: 'recipe-app-33f1d.appspot.com',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz76t1Uq4GbbKIf1V9RyaZ085y-njSlYM',
    appId: '1:243632724029:ios:bd8ee127bf03b6d9f47254',
    messagingSenderId: '243632724029',
    projectId: 'recipe-app-33f1d',
    storageBucket: 'recipe-app-33f1d.appspot.com',
    iosBundleId: 'com.example.recipeApp.RunnerTests',
  );
}
